include: package:lint/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/src/**.g.dart
    - lib/src/**.gr.dart
    - lib/src/**.freezed.dart
linter:
  rules:
    avoid_escaping_inner_quotes: false
    avoid_multiple_declarations_per_line: true
    prefer_single_quotes: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
